language: php
php:
- '7.1'
- '7.2'
before_script:
- composer install
script:
- ./vendor/bin/security-checker security:check
- ./vendor/bin/phpunit --testdox
- ./vendor/bin/phpstan analyse --level 7 ./src ./tests
- ./vendor/bin/phpmd ./src text cleancode,design,unusedcode
